import { createApp } from 'vue';
import './assets/style/index.scss';
import App from './App.vue';
import router from './router';
import service from './service/api';
import components from './components/index.js';
import layoutComponents from './layout/common/index.js';
import ElementPlus from 'element-plus';
import 'element-plus/dist/index.css';
import '@vue-flow/core/dist/style.css';
import '@vue-flow/core/dist/theme-default.css';
import '@vue-flow/minimap/dist/style.css';
import '@vue-flow/controls/dist/style.css';
import { createPinia } from 'pinia';
import './permission';
let app = createApp(App);
app.use(router);
app.use(service);
app.use(components);
app.use(layoutComponents);
app.use(ElementPlus);
app.use(createPinia());
app.mount('#app');
